name: Colourpixels
favicon: null
layout_spectrum: 0.75877
typography_spectrum: 0.7343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a4ea'
    - '#000100'
    - '#fffbf3'
    - '#8099ba'
    - '#743419'
  brandStrength: 0.0625
  lightness: 0.29142890963703394
  saturation: 0.4375
  rhythmicContrast: 0.1370621370151639
purpose: []
